
# add the linters you want stickler to use for this project
linters:
  rubocop:
    display_cop_names: true
    # indicate where is the config file for stylelint
    config: "./rubocop.yml"

files:
  ignore:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
    - "lita_config.rb"
    - "lita-dialog/Rakefile"
    - "lita-dialog/lib/lita-dialog.rb"
    - "lita-dialog/spec/spec_helper.rb"
    - "lita-dialog/lita-dialog.gemspec"
    - "Gemfile"
# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config
# find full documentation here: https://stickler-ci.com/docs
